GET http://localhost:3000/persons HTTP/1.1

###

GET http://localhost:3000/countries HTTP/1.1

###

POST http://localhost:3000/person HTTP/1.1
content-type: application/json

{
   "address": "molave"
}